version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: schedule_bot_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: schedule_bot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - schedule_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schedule_bot_app
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=schedule_bot
    networks:
      - schedule_network

volumes:
  postgres_data:

networks:
  schedule_network:
    driver: bridge 